#!/usr/bin/env node
// lintcha launch index writer (LINTCHA_12 step 3). Reads what the collector wrote (build/launch-day.json by default),
// applies the count floor (n >= 2; the fee recipient namespace additionally d >= 2, because recurrence under one
// deployer is a person relaunching and is neither shown nor stored), checks the result against
// tools/launch-index-schema.json, and writes two frozen files next to numbers.json:
//   site/launch-index.json     per namespace { "<16 hex>": { n, d, first } }, plus v on the skeleton namespaces, compact, keys sorted
//   site/launch-numbers.json   every figure the page prints, by substitution: the window, the counts, the floors
// plus build/launch-index-report.json with the sizes and the sha256 of both files. Deterministic: the same input
// gives the same bytes. Never edited by hand; regenerated by a collector run.
//   node tools/launch-index.mjs [--in build/launch-day.json] [--site site] [--check]
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { validate } from "./launch/schema.mjs";

const here = path.dirname(fileURLToPath(import.meta.url)), root = path.resolve(here, "..");
const require = createRequire(import.meta.url);
const L = require(path.join(root, "site", "launch.js"));
const argv = process.argv.slice(2);
const opt = (name, dflt) => { const i = argv.indexOf("--" + name); return i >= 0 && argv[i + 1] !== undefined && !argv[i + 1].startsWith("--") ? argv[i + 1] : dflt; };
const IN = path.resolve(root, opt("in", path.join("build", "launch-day.json")));
const SITE = path.resolve(root, opt("site", "site"));
const CHECK = argv.includes("--check");
const COUNT_FLOOR = 2;
const SIZE_CEILING = 1500000;   // bytes; the owner's ceiling for a static asset

export function buildIndex(collected) {
  const out = {};
  for (const ns of L.NAMESPACES) {
    const table = collected.tables[ns] || {}, kept = {};
    for (const h of Object.keys(table).sort()) {
      const e = table[h];
      if (e.n < COUNT_FLOOR) continue;
      if (ns === "recipient" && e.d < 2) continue;
      if (ns.endsWith("_skeleton") && !(Number.isInteger(e.v) && e.v >= 1)) throw new Error(ns + " entry without v: the collector output predates the spelling count, rerun it");
      kept[h] = ns.endsWith("_skeleton") ? { n: e.n, d: e.d, first: e.first, v: e.v } : { n: e.n, d: e.d, first: e.first };
    }
    out[ns] = kept;
  }
  return out;
}

export function buildNumbers(collected, index, indexBytes) {
  const w = collected.window, s = collected.six, v = collected.verified, lim = collected.limiter;
  const entries = Object.fromEntries(L.NAMESPACES.map(ns => [ns, Object.keys(index[ns]).length]));
  return {
    chain_id: w.chain_id,
    window: { from_block: w.from, to_block: w.to, blocks: w.blocks, from_time: w.from_time, to_time: w.to_time, from_date: w.from_time.slice(0, 10), to_date: w.to_time.slice(0, 10), hours: Math.round((Date.parse(w.to_time) - Date.parse(w.from_time)) / 3600000) },
    collected: new Date(lim.lastAt).toISOString().slice(0, 10),
    launches_scanned: s.launches_scanned,
    launches_with_a_link: s.launches_with_a_link.count,
    launches_with_a_link_share: s.launches_with_a_link.share,
    links: { distinct_raw: s.distinct_link_values.raw, distinct_folded: s.distinct_link_values.folded, shared_by_more_than_one_deployer_raw: s.link_values_by_more_than_one_deployer.raw, shared_by_more_than_one_deployer_folded: s.link_values_by_more_than_one_deployer.folded },
    tickers_shared_by_more_than_one_deployer: s.tickers_by_more_than_one_deployer,
    lookalike_ticker_pairs: s.lookalike_ticker_pairs.pairs,
    lookalike_ticker_groups: collected.also.lookalike_ticker_groups_v,
    lookalike_name_groups: collected.also.lookalike_name_groups,
    names_shared_by_more_than_one_deployer: collected.also.names_by_more_than_one_deployer,
    logos_shared_by_more_than_one_deployer: collected.also.logos_by_more_than_one_deployer,
    recipients_shared_by_more_than_one_deployer: collected.also.recipients_by_more_than_one_deployer,
    descriptions_compared: collected.also.descriptions_compared,
    descriptions_shared_by_more_than_one_deployer: collected.also.descriptions_by_more_than_one_deployer,
    description_min_words: L.MIN_WORDS,
    count_floor: COUNT_FLOOR,
    index: { entries, entries_total: Object.values(entries).reduce((a, b) => a + b, 0), bytes: indexBytes },
    collector: { calls: lim.calls, http_429: lim.http429, rpc_429: lim.rpc429, retries: lim.retries, other_errors: lim.otherErrors, seconds: lim.seconds, launches_in_log: v.launches_in_log, tokens_readable: v.tokens_readable }
  };
}

const sha = s => crypto.createHash("sha256").update(s).digest("hex");
const compact = o => JSON.stringify(o) + "\n";
const pretty = o => JSON.stringify(o, null, 2) + "\n";

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const collected = JSON.parse(fs.readFileSync(IN, "utf8"));
  const schema = JSON.parse(fs.readFileSync(path.join(here, "launch-index-schema.json"), "utf8"));
  const index = buildIndex(collected);
  const problems = validate(schema, index);
  if (problems.length) { console.error("index fails its schema:\n  " + problems.slice(0, 20).join("\n  ")); process.exit(1); }
  const indexText = compact(index);
  if (indexText.length > SIZE_CEILING) { console.error(`index is ${indexText.length} bytes, over the ${SIZE_CEILING} ceiling`); process.exit(1); }
  const forbidden = indexText.match(/0x[0-9a-fA-F]{40}|https?:|@[A-Za-z0-9_]{2,}/);
  if (forbidden) { console.error("index carries something that is not a counted hash: " + forbidden[0]); process.exit(1); }
  const numbers = buildNumbers(collected, index, indexText.length);
  const numbersText = pretty(numbers);
  const report = { input: path.relative(root, IN).split(path.sep).join("/"), window: numbers.window, count_floor: COUNT_FLOOR, entries: numbers.index.entries, entries_total: numbers.index.entries_total, index_bytes: indexText.length, index_sha256: sha(indexText), numbers_sha256: sha(numbersText), dropped: Object.fromEntries(L.NAMESPACES.map(ns => [ns, Object.keys(collected.tables[ns] || {}).length - Object.keys(index[ns]).length])) };
  if (CHECK) { console.log(JSON.stringify(report, null, 1)); process.exit(0); }
  fs.writeFileSync(path.join(SITE, "launch-index.json"), indexText);
  fs.writeFileSync(path.join(SITE, "launch-numbers.json"), numbersText);
  fs.mkdirSync(path.join(root, "build"), { recursive: true });
  fs.writeFileSync(path.join(root, "build", "launch-index-report.json"), pretty(report));
  console.log(`launch-index.json ${indexText.length} bytes, ${numbers.index.entries_total} entries (${JSON.stringify(numbers.index.entries)}), sha256 ${report.index_sha256.slice(0, 16)}; launch-numbers.json sha256 ${report.numbers_sha256.slice(0, 16)}`);
}
